name: Atlantis Plan

on:
  push:
    branches:
      - '*'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn atlantis plan

